### ISSUE TITLE
Rename initial cluster

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/digitalocean#68]
`jenkins-infra-dosk-agents-<random>`?

Or maybe `doks-agents--<random>`?

Cf https://github.com/jenkins-infra/digitalocean/pull/67#discussion_r973171664 not "private" as it's not really a private cluster, but one dedicated to builds for ci.jenkins.io

**Comment by dduportal** [comment]
🤔 WDYT of `doks-ci.jenkins.io` ?

**Comment by lemeurherve** [comment]
Done.
